pkgname = "db"
output   = "src/db"
wipe     = true
no-tests = true
[psql]
  dbname = "sample_db"
  host   = "localhost"
  port   = 5432
  user   = "user"
  pass   = "password"
  # schema = "myschema"
  sslmode = "disable"