// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	BacknumberTag           string
	Backnumbers             string
	Categories              string
	GooseDBVersion          string
	Tags                    string
	UserFavoritesBacknumber string
	UserFavoritesWorks      string
	UserFollowers           string
	Users                   string
	Works                   string
	WorksCategory           string
}{
	BacknumberTag:           "backnumber_tag",
	Backnumbers:             "backnumbers",
	Categories:              "categories",
	GooseDBVersion:          "goose_db_version",
	Tags:                    "tags",
	UserFavoritesBacknumber: "user_favorites_backnumber",
	UserFavoritesWorks:      "user_favorites_works",
	UserFollowers:           "user_followers",
	Users:                   "users",
	Works:                   "works",
	WorksCategory:           "works_category",
}
