// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserFavoritesWork is an object representing the database table.
type UserFavoritesWork struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UUID      string    `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	UserID    int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	WorksID   int       `boil:"works_id" json:"works_id" toml:"works_id" yaml:"works_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *userFavoritesWorkR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userFavoritesWorkL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserFavoritesWorkColumns = struct {
	ID        string
	UUID      string
	UserID    string
	WorksID   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	UUID:      "uuid",
	UserID:    "user_id",
	WorksID:   "works_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var UserFavoritesWorkTableColumns = struct {
	ID        string
	UUID      string
	UserID    string
	WorksID   string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "user_favorites_works.id",
	UUID:      "user_favorites_works.uuid",
	UserID:    "user_favorites_works.user_id",
	WorksID:   "user_favorites_works.works_id",
	CreatedAt: "user_favorites_works.created_at",
	UpdatedAt: "user_favorites_works.updated_at",
}

// Generated where

var UserFavoritesWorkWhere = struct {
	ID        whereHelperint
	UUID      whereHelperstring
	UserID    whereHelperint
	WorksID   whereHelperint
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "\"user_favorites_works\".\"id\""},
	UUID:      whereHelperstring{field: "\"user_favorites_works\".\"uuid\""},
	UserID:    whereHelperint{field: "\"user_favorites_works\".\"user_id\""},
	WorksID:   whereHelperint{field: "\"user_favorites_works\".\"works_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"user_favorites_works\".\"created_at\""},
	UpdatedAt: whereHelpertime_Time{field: "\"user_favorites_works\".\"updated_at\""},
}

// UserFavoritesWorkRels is where relationship names are stored.
var UserFavoritesWorkRels = struct {
	User string
	Work string
}{
	User: "User",
	Work: "Work",
}

// userFavoritesWorkR is where relationships are stored.
type userFavoritesWorkR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
	Work *Work `boil:"Work" json:"Work" toml:"Work" yaml:"Work"`
}

// NewStruct creates a new relationship struct
func (*userFavoritesWorkR) NewStruct() *userFavoritesWorkR {
	return &userFavoritesWorkR{}
}

// userFavoritesWorkL is where Load methods for each relationship are stored.
type userFavoritesWorkL struct{}

var (
	userFavoritesWorkAllColumns            = []string{"id", "uuid", "user_id", "works_id", "created_at", "updated_at"}
	userFavoritesWorkColumnsWithoutDefault = []string{"uuid", "user_id", "works_id", "created_at", "updated_at"}
	userFavoritesWorkColumnsWithDefault    = []string{"id"}
	userFavoritesWorkPrimaryKeyColumns     = []string{"id"}
)

type (
	// UserFavoritesWorkSlice is an alias for a slice of pointers to UserFavoritesWork.
	// This should almost always be used instead of []UserFavoritesWork.
	UserFavoritesWorkSlice []*UserFavoritesWork
	// UserFavoritesWorkHook is the signature for custom UserFavoritesWork hook methods
	UserFavoritesWorkHook func(context.Context, boil.ContextExecutor, *UserFavoritesWork) error

	userFavoritesWorkQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userFavoritesWorkType                 = reflect.TypeOf(&UserFavoritesWork{})
	userFavoritesWorkMapping              = queries.MakeStructMapping(userFavoritesWorkType)
	userFavoritesWorkPrimaryKeyMapping, _ = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, userFavoritesWorkPrimaryKeyColumns)
	userFavoritesWorkInsertCacheMut       sync.RWMutex
	userFavoritesWorkInsertCache          = make(map[string]insertCache)
	userFavoritesWorkUpdateCacheMut       sync.RWMutex
	userFavoritesWorkUpdateCache          = make(map[string]updateCache)
	userFavoritesWorkUpsertCacheMut       sync.RWMutex
	userFavoritesWorkUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userFavoritesWorkBeforeInsertHooks []UserFavoritesWorkHook
var userFavoritesWorkBeforeUpdateHooks []UserFavoritesWorkHook
var userFavoritesWorkBeforeDeleteHooks []UserFavoritesWorkHook
var userFavoritesWorkBeforeUpsertHooks []UserFavoritesWorkHook

var userFavoritesWorkAfterInsertHooks []UserFavoritesWorkHook
var userFavoritesWorkAfterSelectHooks []UserFavoritesWorkHook
var userFavoritesWorkAfterUpdateHooks []UserFavoritesWorkHook
var userFavoritesWorkAfterDeleteHooks []UserFavoritesWorkHook
var userFavoritesWorkAfterUpsertHooks []UserFavoritesWorkHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserFavoritesWork) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserFavoritesWork) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserFavoritesWork) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserFavoritesWork) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserFavoritesWork) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserFavoritesWork) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserFavoritesWork) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserFavoritesWork) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserFavoritesWork) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userFavoritesWorkAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserFavoritesWorkHook registers your hook function for all future operations.
func AddUserFavoritesWorkHook(hookPoint boil.HookPoint, userFavoritesWorkHook UserFavoritesWorkHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		userFavoritesWorkBeforeInsertHooks = append(userFavoritesWorkBeforeInsertHooks, userFavoritesWorkHook)
	case boil.BeforeUpdateHook:
		userFavoritesWorkBeforeUpdateHooks = append(userFavoritesWorkBeforeUpdateHooks, userFavoritesWorkHook)
	case boil.BeforeDeleteHook:
		userFavoritesWorkBeforeDeleteHooks = append(userFavoritesWorkBeforeDeleteHooks, userFavoritesWorkHook)
	case boil.BeforeUpsertHook:
		userFavoritesWorkBeforeUpsertHooks = append(userFavoritesWorkBeforeUpsertHooks, userFavoritesWorkHook)
	case boil.AfterInsertHook:
		userFavoritesWorkAfterInsertHooks = append(userFavoritesWorkAfterInsertHooks, userFavoritesWorkHook)
	case boil.AfterSelectHook:
		userFavoritesWorkAfterSelectHooks = append(userFavoritesWorkAfterSelectHooks, userFavoritesWorkHook)
	case boil.AfterUpdateHook:
		userFavoritesWorkAfterUpdateHooks = append(userFavoritesWorkAfterUpdateHooks, userFavoritesWorkHook)
	case boil.AfterDeleteHook:
		userFavoritesWorkAfterDeleteHooks = append(userFavoritesWorkAfterDeleteHooks, userFavoritesWorkHook)
	case boil.AfterUpsertHook:
		userFavoritesWorkAfterUpsertHooks = append(userFavoritesWorkAfterUpsertHooks, userFavoritesWorkHook)
	}
}

// One returns a single userFavoritesWork record from the query.
func (q userFavoritesWorkQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserFavoritesWork, error) {
	o := &UserFavoritesWork{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for user_favorites_works")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserFavoritesWork records from the query.
func (q userFavoritesWorkQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserFavoritesWorkSlice, error) {
	var o []*UserFavoritesWork

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to UserFavoritesWork slice")
	}

	if len(userFavoritesWorkAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserFavoritesWork records in the query.
func (q userFavoritesWorkQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count user_favorites_works rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userFavoritesWorkQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if user_favorites_works exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserFavoritesWork) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// Work pointed to by the foreign key.
func (o *UserFavoritesWork) Work(mods ...qm.QueryMod) workQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.WorksID),
	}

	queryMods = append(queryMods, mods...)

	query := Works(queryMods...)
	queries.SetFrom(query.Query, "\"works\"")

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userFavoritesWorkL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserFavoritesWork interface{}, mods queries.Applicator) error {
	var slice []*UserFavoritesWork
	var object *UserFavoritesWork

	if singular {
		object = maybeUserFavoritesWork.(*UserFavoritesWork)
	} else {
		slice = *maybeUserFavoritesWork.(*[]*UserFavoritesWork)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userFavoritesWorkR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userFavoritesWorkR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userFavoritesWorkAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserFavoritesWorks = append(foreign.R.UserFavoritesWorks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserFavoritesWorks = append(foreign.R.UserFavoritesWorks, local)
				break
			}
		}
	}

	return nil
}

// LoadWork allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userFavoritesWorkL) LoadWork(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserFavoritesWork interface{}, mods queries.Applicator) error {
	var slice []*UserFavoritesWork
	var object *UserFavoritesWork

	if singular {
		object = maybeUserFavoritesWork.(*UserFavoritesWork)
	} else {
		slice = *maybeUserFavoritesWork.(*[]*UserFavoritesWork)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userFavoritesWorkR{}
		}
		args = append(args, object.WorksID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userFavoritesWorkR{}
			}

			for _, a := range args {
				if a == obj.WorksID {
					continue Outer
				}
			}

			args = append(args, obj.WorksID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`works`),
		qm.WhereIn(`works.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Work")
	}

	var resultSlice []*Work
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Work")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for works")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for works")
	}

	if len(userFavoritesWorkAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Work = foreign
		if foreign.R == nil {
			foreign.R = &workR{}
		}
		foreign.R.UserFavoritesWorks = append(foreign.R.UserFavoritesWorks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.WorksID == foreign.ID {
				local.R.Work = foreign
				if foreign.R == nil {
					foreign.R = &workR{}
				}
				foreign.R.UserFavoritesWorks = append(foreign.R.UserFavoritesWorks, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userFavoritesWork to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserFavoritesWorks.
func (o *UserFavoritesWork) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_favorites_works\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userFavoritesWorkPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userFavoritesWorkR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserFavoritesWorks: UserFavoritesWorkSlice{o},
		}
	} else {
		related.R.UserFavoritesWorks = append(related.R.UserFavoritesWorks, o)
	}

	return nil
}

// SetWork of the userFavoritesWork to the related item.
// Sets o.R.Work to related.
// Adds o to related.R.UserFavoritesWorks.
func (o *UserFavoritesWork) SetWork(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Work) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_favorites_works\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"works_id"}),
		strmangle.WhereClause("\"", "\"", 2, userFavoritesWorkPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.WorksID = related.ID
	if o.R == nil {
		o.R = &userFavoritesWorkR{
			Work: related,
		}
	} else {
		o.R.Work = related
	}

	if related.R == nil {
		related.R = &workR{
			UserFavoritesWorks: UserFavoritesWorkSlice{o},
		}
	} else {
		related.R.UserFavoritesWorks = append(related.R.UserFavoritesWorks, o)
	}

	return nil
}

// UserFavoritesWorks retrieves all the records using an executor.
func UserFavoritesWorks(mods ...qm.QueryMod) userFavoritesWorkQuery {
	mods = append(mods, qm.From("\"user_favorites_works\""))
	return userFavoritesWorkQuery{NewQuery(mods...)}
}

// FindUserFavoritesWork retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserFavoritesWork(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*UserFavoritesWork, error) {
	userFavoritesWorkObj := &UserFavoritesWork{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_favorites_works\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userFavoritesWorkObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from user_favorites_works")
	}

	if err = userFavoritesWorkObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userFavoritesWorkObj, err
	}

	return userFavoritesWorkObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserFavoritesWork) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_favorites_works provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userFavoritesWorkColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userFavoritesWorkInsertCacheMut.RLock()
	cache, cached := userFavoritesWorkInsertCache[key]
	userFavoritesWorkInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userFavoritesWorkAllColumns,
			userFavoritesWorkColumnsWithDefault,
			userFavoritesWorkColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_favorites_works\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_favorites_works\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into user_favorites_works")
	}

	if !cached {
		userFavoritesWorkInsertCacheMut.Lock()
		userFavoritesWorkInsertCache[key] = cache
		userFavoritesWorkInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserFavoritesWork.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserFavoritesWork) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userFavoritesWorkUpdateCacheMut.RLock()
	cache, cached := userFavoritesWorkUpdateCache[key]
	userFavoritesWorkUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userFavoritesWorkAllColumns,
			userFavoritesWorkPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update user_favorites_works, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_favorites_works\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userFavoritesWorkPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, append(wl, userFavoritesWorkPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update user_favorites_works row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for user_favorites_works")
	}

	if !cached {
		userFavoritesWorkUpdateCacheMut.Lock()
		userFavoritesWorkUpdateCache[key] = cache
		userFavoritesWorkUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userFavoritesWorkQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for user_favorites_works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for user_favorites_works")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserFavoritesWorkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritesWorkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_favorites_works\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userFavoritesWorkPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in userFavoritesWork slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all userFavoritesWork")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserFavoritesWork) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no user_favorites_works provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userFavoritesWorkColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userFavoritesWorkUpsertCacheMut.RLock()
	cache, cached := userFavoritesWorkUpsertCache[key]
	userFavoritesWorkUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userFavoritesWorkAllColumns,
			userFavoritesWorkColumnsWithDefault,
			userFavoritesWorkColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userFavoritesWorkAllColumns,
			userFavoritesWorkPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert user_favorites_works, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userFavoritesWorkPrimaryKeyColumns))
			copy(conflict, userFavoritesWorkPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_favorites_works\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userFavoritesWorkType, userFavoritesWorkMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert user_favorites_works")
	}

	if !cached {
		userFavoritesWorkUpsertCacheMut.Lock()
		userFavoritesWorkUpsertCache[key] = cache
		userFavoritesWorkUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single UserFavoritesWork record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserFavoritesWork) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no UserFavoritesWork provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userFavoritesWorkPrimaryKeyMapping)
	sql := "DELETE FROM \"user_favorites_works\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from user_favorites_works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for user_favorites_works")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userFavoritesWorkQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no userFavoritesWorkQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from user_favorites_works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_favorites_works")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserFavoritesWorkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userFavoritesWorkBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritesWorkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_favorites_works\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userFavoritesWorkPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from userFavoritesWork slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for user_favorites_works")
	}

	if len(userFavoritesWorkAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserFavoritesWork) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserFavoritesWork(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserFavoritesWorkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserFavoritesWorkSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userFavoritesWorkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_favorites_works\".* FROM \"user_favorites_works\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userFavoritesWorkPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in UserFavoritesWorkSlice")
	}

	*o = slice

	return nil
}

// UserFavoritesWorkExists checks if the UserFavoritesWork row exists.
func UserFavoritesWorkExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_favorites_works\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if user_favorites_works exists")
	}

	return exists, nil
}
