// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Work is an object representing the database table.
type Work struct {
	ID             int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	UUID           string    `boil:"uuid" json:"uuid" toml:"uuid" yaml:"uuid"`
	UserID         int       `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Title          string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	Description    string    `boil:"description" json:"description" toml:"description" yaml:"description"`
	BookmarksCount int       `boil:"bookmarks_count" json:"bookmarks_count" toml:"bookmarks_count" yaml:"bookmarks_count"`
	ThumbnailURL   string    `boil:"thumbnail_url" json:"thumbnail_url" toml:"thumbnail_url" yaml:"thumbnail_url"`
	Public         bool      `boil:"public" json:"public" toml:"public" yaml:"public"`
	WorksURL       string    `boil:"works_url" json:"works_url" toml:"works_url" yaml:"works_url"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *workR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L workL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WorkColumns = struct {
	ID             string
	UUID           string
	UserID         string
	Title          string
	Description    string
	BookmarksCount string
	ThumbnailURL   string
	Public         string
	WorksURL       string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	UUID:           "uuid",
	UserID:         "user_id",
	Title:          "title",
	Description:    "description",
	BookmarksCount: "bookmarks_count",
	ThumbnailURL:   "thumbnail_url",
	Public:         "public",
	WorksURL:       "works_url",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var WorkTableColumns = struct {
	ID             string
	UUID           string
	UserID         string
	Title          string
	Description    string
	BookmarksCount string
	ThumbnailURL   string
	Public         string
	WorksURL       string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "works.id",
	UUID:           "works.uuid",
	UserID:         "works.user_id",
	Title:          "works.title",
	Description:    "works.description",
	BookmarksCount: "works.bookmarks_count",
	ThumbnailURL:   "works.thumbnail_url",
	Public:         "works.public",
	WorksURL:       "works.works_url",
	CreatedAt:      "works.created_at",
	UpdatedAt:      "works.updated_at",
}

// Generated where

var WorkWhere = struct {
	ID             whereHelperint
	UUID           whereHelperstring
	UserID         whereHelperint
	Title          whereHelperstring
	Description    whereHelperstring
	BookmarksCount whereHelperint
	ThumbnailURL   whereHelperstring
	Public         whereHelperbool
	WorksURL       whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint{field: "\"works\".\"id\""},
	UUID:           whereHelperstring{field: "\"works\".\"uuid\""},
	UserID:         whereHelperint{field: "\"works\".\"user_id\""},
	Title:          whereHelperstring{field: "\"works\".\"title\""},
	Description:    whereHelperstring{field: "\"works\".\"description\""},
	BookmarksCount: whereHelperint{field: "\"works\".\"bookmarks_count\""},
	ThumbnailURL:   whereHelperstring{field: "\"works\".\"thumbnail_url\""},
	Public:         whereHelperbool{field: "\"works\".\"public\""},
	WorksURL:       whereHelperstring{field: "\"works\".\"works_url\""},
	CreatedAt:      whereHelpertime_Time{field: "\"works\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"works\".\"updated_at\""},
}

// WorkRels is where relationship names are stored.
var WorkRels = struct {
	User               string
	Backnumbers        string
	UserFavoritesWorks string
}{
	User:               "User",
	Backnumbers:        "Backnumbers",
	UserFavoritesWorks: "UserFavoritesWorks",
}

// workR is where relationships are stored.
type workR struct {
	User               *User                  `boil:"User" json:"User" toml:"User" yaml:"User"`
	Backnumbers        BacknumberSlice        `boil:"Backnumbers" json:"Backnumbers" toml:"Backnumbers" yaml:"Backnumbers"`
	UserFavoritesWorks UserFavoritesWorkSlice `boil:"UserFavoritesWorks" json:"UserFavoritesWorks" toml:"UserFavoritesWorks" yaml:"UserFavoritesWorks"`
}

// NewStruct creates a new relationship struct
func (*workR) NewStruct() *workR {
	return &workR{}
}

// workL is where Load methods for each relationship are stored.
type workL struct{}

var (
	workAllColumns            = []string{"id", "uuid", "user_id", "title", "description", "bookmarks_count", "thumbnail_url", "public", "works_url", "created_at", "updated_at"}
	workColumnsWithoutDefault = []string{"uuid", "user_id", "title", "description", "thumbnail_url", "works_url", "created_at", "updated_at"}
	workColumnsWithDefault    = []string{"id", "bookmarks_count", "public"}
	workPrimaryKeyColumns     = []string{"id"}
)

type (
	// WorkSlice is an alias for a slice of pointers to Work.
	// This should almost always be used instead of []Work.
	WorkSlice []*Work
	// WorkHook is the signature for custom Work hook methods
	WorkHook func(context.Context, boil.ContextExecutor, *Work) error

	workQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	workType                 = reflect.TypeOf(&Work{})
	workMapping              = queries.MakeStructMapping(workType)
	workPrimaryKeyMapping, _ = queries.BindMapping(workType, workMapping, workPrimaryKeyColumns)
	workInsertCacheMut       sync.RWMutex
	workInsertCache          = make(map[string]insertCache)
	workUpdateCacheMut       sync.RWMutex
	workUpdateCache          = make(map[string]updateCache)
	workUpsertCacheMut       sync.RWMutex
	workUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var workBeforeInsertHooks []WorkHook
var workBeforeUpdateHooks []WorkHook
var workBeforeDeleteHooks []WorkHook
var workBeforeUpsertHooks []WorkHook

var workAfterInsertHooks []WorkHook
var workAfterSelectHooks []WorkHook
var workAfterUpdateHooks []WorkHook
var workAfterDeleteHooks []WorkHook
var workAfterUpsertHooks []WorkHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Work) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Work) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Work) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Work) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Work) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Work) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Work) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Work) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Work) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range workAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddWorkHook registers your hook function for all future operations.
func AddWorkHook(hookPoint boil.HookPoint, workHook WorkHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		workBeforeInsertHooks = append(workBeforeInsertHooks, workHook)
	case boil.BeforeUpdateHook:
		workBeforeUpdateHooks = append(workBeforeUpdateHooks, workHook)
	case boil.BeforeDeleteHook:
		workBeforeDeleteHooks = append(workBeforeDeleteHooks, workHook)
	case boil.BeforeUpsertHook:
		workBeforeUpsertHooks = append(workBeforeUpsertHooks, workHook)
	case boil.AfterInsertHook:
		workAfterInsertHooks = append(workAfterInsertHooks, workHook)
	case boil.AfterSelectHook:
		workAfterSelectHooks = append(workAfterSelectHooks, workHook)
	case boil.AfterUpdateHook:
		workAfterUpdateHooks = append(workAfterUpdateHooks, workHook)
	case boil.AfterDeleteHook:
		workAfterDeleteHooks = append(workAfterDeleteHooks, workHook)
	case boil.AfterUpsertHook:
		workAfterUpsertHooks = append(workAfterUpsertHooks, workHook)
	}
}

// One returns a single work record from the query.
func (q workQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Work, error) {
	o := &Work{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: failed to execute a one query for works")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Work records from the query.
func (q workQuery) All(ctx context.Context, exec boil.ContextExecutor) (WorkSlice, error) {
	var o []*Work

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "db: failed to assign all query results to Work slice")
	}

	if len(workAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Work records in the query.
func (q workQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to count works rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q workQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "db: failed to check if works exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Work) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Users(queryMods...)
	queries.SetFrom(query.Query, "\"users\"")

	return query
}

// Backnumbers retrieves all the backnumber's Backnumbers with an executor.
func (o *Work) Backnumbers(mods ...qm.QueryMod) backnumberQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"backnumbers\".\"works_id\"=?", o.ID),
	)

	query := Backnumbers(queryMods...)
	queries.SetFrom(query.Query, "\"backnumbers\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"backnumbers\".*"})
	}

	return query
}

// UserFavoritesWorks retrieves all the user_favorites_work's UserFavoritesWorks with an executor.
func (o *Work) UserFavoritesWorks(mods ...qm.QueryMod) userFavoritesWorkQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"user_favorites_works\".\"works_id\"=?", o.ID),
	)

	query := UserFavoritesWorks(queryMods...)
	queries.SetFrom(query.Query, "\"user_favorites_works\"")

	if len(queries.GetSelect(query.Query)) == 0 {
		queries.SetSelect(query.Query, []string{"\"user_favorites_works\".*"})
	}

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (workL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		object = maybeWork.(*Work)
	} else {
		slice = *maybeWork.(*[]*Work)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(workAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Works = append(foreign.R.Works, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Works = append(foreign.R.Works, local)
				break
			}
		}
	}

	return nil
}

// LoadBacknumbers allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workL) LoadBacknumbers(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		object = maybeWork.(*Work)
	} else {
		slice = *maybeWork.(*[]*Work)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`backnumbers`),
		qm.WhereIn(`backnumbers.works_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load backnumbers")
	}

	var resultSlice []*Backnumber
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice backnumbers")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on backnumbers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for backnumbers")
	}

	if len(backnumberAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Backnumbers = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &backnumberR{}
			}
			foreign.R.Work = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorksID {
				local.R.Backnumbers = append(local.R.Backnumbers, foreign)
				if foreign.R == nil {
					foreign.R = &backnumberR{}
				}
				foreign.R.Work = local
				break
			}
		}
	}

	return nil
}

// LoadUserFavoritesWorks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (workL) LoadUserFavoritesWorks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWork interface{}, mods queries.Applicator) error {
	var slice []*Work
	var object *Work

	if singular {
		object = maybeWork.(*Work)
	} else {
		slice = *maybeWork.(*[]*Work)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &workR{}
		}
		args = append(args, object.ID)
	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &workR{}
			}

			for _, a := range args {
				if a == obj.ID {
					continue Outer
				}
			}

			args = append(args, obj.ID)
		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`user_favorites_works`),
		qm.WhereIn(`user_favorites_works.works_id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load user_favorites_works")
	}

	var resultSlice []*UserFavoritesWork
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice user_favorites_works")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on user_favorites_works")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for user_favorites_works")
	}

	if len(userFavoritesWorkAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.UserFavoritesWorks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &userFavoritesWorkR{}
			}
			foreign.R.Work = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.WorksID {
				local.R.UserFavoritesWorks = append(local.R.UserFavoritesWorks, foreign)
				if foreign.R == nil {
					foreign.R = &userFavoritesWorkR{}
				}
				foreign.R.Work = local
				break
			}
		}
	}

	return nil
}

// SetUser of the work to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Works.
func (o *Work) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"works\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, workPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &workR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Works: WorkSlice{o},
		}
	} else {
		related.R.Works = append(related.R.Works, o)
	}

	return nil
}

// AddBacknumbers adds the given related objects to the existing relationships
// of the work, optionally inserting them as new records.
// Appends related to o.R.Backnumbers.
// Sets related.R.Work appropriately.
func (o *Work) AddBacknumbers(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Backnumber) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorksID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"backnumbers\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"works_id"}),
				strmangle.WhereClause("\"", "\"", 2, backnumberPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorksID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workR{
			Backnumbers: related,
		}
	} else {
		o.R.Backnumbers = append(o.R.Backnumbers, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &backnumberR{
				Work: o,
			}
		} else {
			rel.R.Work = o
		}
	}
	return nil
}

// AddUserFavoritesWorks adds the given related objects to the existing relationships
// of the work, optionally inserting them as new records.
// Appends related to o.R.UserFavoritesWorks.
// Sets related.R.Work appropriately.
func (o *Work) AddUserFavoritesWorks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*UserFavoritesWork) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.WorksID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"user_favorites_works\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"works_id"}),
				strmangle.WhereClause("\"", "\"", 2, userFavoritesWorkPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.WorksID = o.ID
		}
	}

	if o.R == nil {
		o.R = &workR{
			UserFavoritesWorks: related,
		}
	} else {
		o.R.UserFavoritesWorks = append(o.R.UserFavoritesWorks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &userFavoritesWorkR{
				Work: o,
			}
		} else {
			rel.R.Work = o
		}
	}
	return nil
}

// Works retrieves all the records using an executor.
func Works(mods ...qm.QueryMod) workQuery {
	mods = append(mods, qm.From("\"works\""))
	return workQuery{NewQuery(mods...)}
}

// FindWork retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWork(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Work, error) {
	workObj := &Work{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"works\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, workObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "db: unable to select from works")
	}

	if err = workObj.doAfterSelectHooks(ctx, exec); err != nil {
		return workObj, err
	}

	return workObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Work) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("db: no works provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	workInsertCacheMut.RLock()
	cache, cached := workInsertCache[key]
	workInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			workAllColumns,
			workColumnsWithDefault,
			workColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(workType, workMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(workType, workMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"works\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"works\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "db: unable to insert into works")
	}

	if !cached {
		workInsertCacheMut.Lock()
		workInsertCache[key] = cache
		workInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Work.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Work) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	workUpdateCacheMut.RLock()
	cache, cached := workUpdateCache[key]
	workUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			workAllColumns,
			workPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("db: unable to update works, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"works\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, workPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(workType, workMapping, append(wl, workPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update works row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by update for works")
	}

	if !cached {
		workUpdateCacheMut.Lock()
		workUpdateCache[key] = cache
		workUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q workQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all for works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected for works")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WorkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("db: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"works\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, workPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to update all in work slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to retrieve rows affected all in update all work")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Work) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("db: no works provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(workColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	workUpsertCacheMut.RLock()
	cache, cached := workUpsertCache[key]
	workUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			workAllColumns,
			workColumnsWithDefault,
			workColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			workAllColumns,
			workPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("db: unable to upsert works, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(workPrimaryKeyColumns))
			copy(conflict, workPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"works\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(workType, workMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(workType, workMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "db: unable to upsert works")
	}

	if !cached {
		workUpsertCacheMut.Lock()
		workUpsertCache[key] = cache
		workUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Work record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Work) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("db: no Work provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), workPrimaryKeyMapping)
	sql := "DELETE FROM \"works\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete from works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by delete for works")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q workQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("db: no workQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from works")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for works")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WorkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(workBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"works\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "db: unable to delete all from work slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "db: failed to get rows affected by deleteall for works")
	}

	if len(workAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Work) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWork(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WorkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WorkSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), workPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"works\".* FROM \"works\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, workPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "db: unable to reload all in WorkSlice")
	}

	*o = slice

	return nil
}

// WorkExists checks if the Work row exists.
func WorkExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"works\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "db: unable to check if works exists")
	}

	return exists, nil
}
